#!/usr/bin/env python3
"""
Script pour créer la base de données exactement selon le fichier PDF fourni par l'utilisateur
Toutes les traductions et catégories correspondent exactement au document original
"""

import os
from pymongo import MongoClient
from datetime import datetime

# MongoDB connection
MONGO_URL = os.getenv("MONGO_URL", "mongodb://localhost:27017/mayotte_app")
client = MongoClient(MONGO_URL)
db = client.mayotte_app
words_collection = db.words

def create_database_from_pdf():
    """Créer la base de données exactement selon le fichier PDF"""
    
    # Vider la base existante
    words_collection.delete_many({})
    
    # Vocabulaire exact du fichier PDF - organisé par pages
    pdf_vocabulary = [
        # PAGE 1 - NATURE
        {"french": "pente/colline/mont", "shimaore": "mlima", "kibouchi": "boungou", "category": "nature", "image_url": "⛰️", "difficulty": 1},
        {"french": "lune", "shimaore": "mwézi", "kibouchi": "fandzava", "category": "nature", "image_url": "🌙", "difficulty": 1},
        {"french": "étoile", "shimaore": "gnora", "kibouchi": "lakintagna", "category": "nature", "image_url": "⭐", "difficulty": 1},
        {"french": "sable", "shimaore": "mtsanga", "kibouchi": "fasigni", "category": "nature", "image_url": "🏖️", "difficulty": 1},
        {"french": "vague", "shimaore": "dhouja", "kibouchi": "houndza/riaka", "category": "nature", "image_url": "🌊", "difficulty": 1},
        {"french": "vent", "shimaore": "pévo", "kibouchi": "tsikou", "category": "nature", "image_url": "🌬️", "difficulty": 1},
        {"french": "pluie", "shimaore": "vhoua", "kibouchi": "mahaléni", "category": "nature", "image_url": "🌧️", "difficulty": 1},
        {"french": "mangrove", "shimaore": "mhonko", "kibouchi": "honkou", "category": "nature", "image_url": "🌿", "difficulty": 1},
        {"french": "corail", "shimaore": "soiyi", "kibouchi": "soiyi", "category": "nature", "image_url": "🪸", "difficulty": 1},
        {"french": "barrière de corail", "shimaore": "caléni", "kibouchi": "caléni", "category": "nature", "image_url": "🪸", "difficulty": 2},
        {"french": "tempête", "shimaore": "darouba", "kibouchi": "tsikou", "category": "nature", "image_url": "⛈️", "difficulty": 1},
        {"french": "rivière", "shimaore": "mouro", "kibouchi": "mouroni", "category": "nature", "image_url": "🏞️", "difficulty": 1},
        {"french": "pont", "shimaore": "daradja", "kibouchi": "daradja", "category": "nature", "image_url": "🌉", "difficulty": 1},
        {"french": "nuage", "shimaore": "wingou", "kibouchi": "vingou", "category": "nature", "image_url": "☁️", "difficulty": 1},
        {"french": "arc en ciel", "shimaore": "mcacamba", "kibouchi": "atihala", "category": "nature", "image_url": "🌈", "difficulty": 1},
        {"french": "campagne/forêt", "shimaore": "malavouni", "kibouchi": "vatou", "category": "nature", "image_url": "🌳", "difficulty": 1},
        {"french": "caillou/pierre/rocher", "shimaore": "bwé", "kibouchi": "kètraka", "category": "nature", "image_url": "🪨", "difficulty": 1},
        {"french": "plateau", "shimaore": "bandra", "kibouchi": "lalagna", "category": "nature", "image_url": "🏔️", "difficulty": 1},
        {"french": "herbe", "shimaore": "foulera", "kibouchi": "foulera", "category": "nature", "image_url": "🌱", "difficulty": 1},
        {"french": "chemin/sentier/parcours", "shimaore": "ndzia", "kibouchi": "haitri", "category": "nature", "image_url": "🛤️", "difficulty": 1},
        {"french": "fleur", "shimaore": "malavou", "kibouchi": "foulera", "category": "nature", "image_url": "🌸", "difficulty": 1},
        {"french": "soleil", "shimaore": "jouwa", "kibouchi": "zouva", "category": "nature", "image_url": "☀️", "difficulty": 1},
        {"french": "mer", "shimaore": "bahari", "kibouchi": "bahari", "category": "nature", "image_url": "🌊", "difficulty": 1},
        {"french": "plage", "shimaore": "mtsangani", "kibouchi": "fassigni", "category": "nature", "image_url": "🏖️", "difficulty": 1},
        {"french": "arbre", "shimaore": "mwiri", "kibouchi": "kakazou", "category": "nature", "image_url": "🌳", "difficulty": 1},
        {"french": "rue/route", "shimaore": "paré", "kibouchi": "paré", "category": "nature", "image_url": "🛣️", "difficulty": 1},
        {"french": "bananier", "shimaore": "trindri", "kibouchi": "voudi ni hountsi", "category": "nature", "image_url": "🌴", "difficulty": 1},
        {"french": "feuille", "shimaore": "mawoini", "kibouchi": "hayitri", "category": "nature", "image_url": "🍃", "difficulty": 1},
        {"french": "branche", "shimaore": "trahi", "kibouchi": "trahi", "category": "nature", "image_url": "🌿", "difficulty": 1},
        {"french": "tornade", "shimaore": "ouzimouyi", "kibouchi": "tsikou soulaimana", "category": "nature", "image_url": "🌪️", "difficulty": 1},
        {"french": "cocotier", "shimaore": "m'nadzi", "kibouchi": "voudi ni vwaniou", "category": "nature", "image_url": "🌴", "difficulty": 1},
        {"french": "arbre à pain", "shimaore": "m'frampé", "kibouchi": "voudi ni frampé", "category": "nature", "image_url": "🌳", "difficulty": 1},
        {"french": "baobab", "shimaore": "m'bouyou", "kibouchi": "voudi ni bouyou", "category": "nature", "image_url": "🌳", "difficulty": 1},
        {"french": "bambou", "shimaore": "m'banbo", "kibouchi": "valiha", "category": "nature", "image_url": "🎋", "difficulty": 1},
        {"french": "manguier", "shimaore": "m'manga", "kibouchi": "voudi ni manga", "category": "nature", "image_url": "🌳", "difficulty": 1},
        {"french": "jacquier", "shimaore": "m'fénéssi", "kibouchi": "voudi ni finéssi", "category": "nature", "image_url": "🌳", "difficulty": 1},
        {"french": "terre", "shimaore": "sol", "kibouchi": "fotaka", "category": "nature", "image_url": "🌍", "difficulty": 1},
        {"french": "érosion", "shimaore": "chivandré ya tsi", "kibouchi": "padza", "category": "nature", "image_url": "🌊", "difficulty": 2},
        {"french": "marée basse", "shimaore": "maji yavo", "kibouchi": "ranou mèki", "category": "nature", "image_url": "🌊", "difficulty": 2},
        {"french": "platier", "shimaore": "padza", "kibouchi": "kaléni", "category": "nature", "image_url": "🪨", "difficulty": 2},
        {"french": "marée haute", "shimaore": "maji yamalé", "kibouchi": "ranou fénou", "category": "nature", "image_url": "🌊", "difficulty": 2},
        {"french": "inondé", "shimaore": "kalé", "kibouchi": "dobou", "category": "nature", "image_url": "🌊", "difficulty": 2},
        {"french": "sauvage", "shimaore": "ourora", "kibouchi": "dif", "category": "nature", "image_url": "🌿", "difficulty": 1},
        {"french": "canne à sucre", "shimaore": "nyéha", "kibouchi": "fari", "category": "nature", "image_url": "🌾", "difficulty": 1},
        {"french": "fagot", "shimaore": "mouwoi", "kibouchi": "azoumati", "category": "nature", "image_url": "🪵", "difficulty": 1},
        {"french": "pirogue", "shimaore": "kouni", "kibouchi": "lakan", "category": "nature", "image_url": "🛶", "difficulty": 1},
        {"french": "vedette", "shimaore": "kwassa kwassa", "kibouchi": "vidéti", "category": "nature", "image_url": "🚤", "difficulty": 1},
        {"french": "école", "shimaore": "licoli", "kibouchi": "licoli", "category": "humain", "image_url": "🏫", "difficulty": 1},
        {"french": "école coranique", "shimaore": "shioni", "kibouchi": "kioni", "category": "humain", "image_url": "🕌", "difficulty": 1},

        # PAGE 2 - CHIFFRES ET ANIMAUX
        {"french": "un", "shimaore": "moja", "kibouchi": "moja", "category": "chiffre", "image_url": "1️⃣", "difficulty": 1},
        {"french": "deux", "shimaore": "mbili", "kibouchi": "mbili", "category": "chiffre", "image_url": "2️⃣", "difficulty": 1},
        {"french": "trois", "shimaore": "trarou", "kibouchi": "trarou", "category": "chiffre", "image_url": "3️⃣", "difficulty": 1},
        {"french": "quatre", "shimaore": "nhé", "kibouchi": "nhé", "category": "chiffre", "image_url": "4️⃣", "difficulty": 1},
        {"french": "cinq", "shimaore": "tsano", "kibouchi": "tsano", "category": "chiffre", "image_url": "5️⃣", "difficulty": 1},
        {"french": "six", "shimaore": "sita", "kibouchi": "sita", "category": "chiffre", "image_url": "6️⃣", "difficulty": 1},
        {"french": "sept", "shimaore": "saba", "kibouchi": "saba", "category": "chiffre", "image_url": "7️⃣", "difficulty": 1},
        {"french": "huit", "shimaore": "nané", "kibouchi": "nané", "category": "chiffre", "image_url": "8️⃣", "difficulty": 1},
        {"french": "neuf", "shimaore": "chendra", "kibouchi": "chendra", "category": "chiffre", "image_url": "9️⃣", "difficulty": 1},
        {"french": "dix", "shimaore": "koumi", "kibouchi": "koumi", "category": "chiffre", "image_url": "🔟", "difficulty": 1},
        {"french": "onze", "shimaore": "koumi na moja", "kibouchi": "", "category": "chiffre", "image_url": "1️⃣1️⃣", "difficulty": 2},
        {"french": "douze", "shimaore": "koumi na mbili", "kibouchi": "", "category": "chiffre", "image_url": "1️⃣2️⃣", "difficulty": 2},
        {"french": "treize", "shimaore": "koumi na trarou", "kibouchi": "", "category": "chiffre", "image_url": "1️⃣3️⃣", "difficulty": 2},
        {"french": "quatorze", "shimaore": "koumi na nhé", "kibouchi": "", "category": "chiffre", "image_url": "1️⃣4️⃣", "difficulty": 2},
        {"french": "quinze", "shimaore": "koumi na tsano", "kibouchi": "", "category": "chiffre", "image_url": "1️⃣5️⃣", "difficulty": 2},
        {"french": "seize", "shimaore": "koumi na sita", "kibouchi": "", "category": "chiffre", "image_url": "1️⃣6️⃣", "difficulty": 2},
        {"french": "dix-sept", "shimaore": "koumi na saba", "kibouchi": "", "category": "chiffre", "image_url": "1️⃣7️⃣", "difficulty": 2},
        {"french": "dix-huit", "shimaore": "koumi na nané", "kibouchi": "", "category": "chiffre", "image_url": "1️⃣8️⃣", "difficulty": 2},
        {"french": "dix-neuf", "shimaore": "koumi na chendra", "kibouchi": "", "category": "chiffre", "image_url": "1️⃣9️⃣", "difficulty": 2},
        {"french": "vingt", "shimaore": "chirini", "kibouchi": "", "category": "chiffre", "image_url": "2️⃣0️⃣", "difficulty": 2},

        # ANIMAUX - PAGE 2
        {"french": "cochon", "shimaore": "pouroukou", "kibouchi": "", "category": "animal", "image_url": "🐷", "difficulty": 1},
        {"french": "margouillat", "shimaore": "kasangwe", "kibouchi": "", "category": "animal", "image_url": "🦎", "difficulty": 1},
        {"french": "niochi", "shimaore": "niochi", "kibouchi": "", "category": "animal", "image_url": "🐝", "difficulty": 1},
        {"french": "abeille", "shimaore": "n'ochi", "kibouchi": "", "category": "animal", "image_url": "🐝", "difficulty": 1},
        {"french": "chat", "shimaore": "paha", "kibouchi": "", "category": "animal", "image_url": "🐱", "difficulty": 1},
        {"french": "rat", "shimaore": "pouhou", "kibouchi": "", "category": "animal", "image_url": "🐭", "difficulty": 1},
        {"french": "escargot", "shimaore": "kwa", "kibouchi": "", "category": "animal", "image_url": "🐌", "difficulty": 1},
        {"french": "lion", "shimaore": "simba", "kibouchi": "", "category": "animal", "image_url": "🦁", "difficulty": 1},
        {"french": "grenouille", "shimaore": "shiwatrotro", "kibouchi": "", "category": "animal", "image_url": "🐸", "difficulty": 1},
        {"french": "oiseau", "shimaore": "gnougni", "kibouchi": "", "category": "animal", "image_url": "🐦", "difficulty": 1},
        {"french": "chien", "shimaore": "mbwa", "kibouchi": "", "category": "animal", "image_url": "🐶", "difficulty": 1},
        {"french": "poisson", "shimaore": "fi", "kibouchi": "", "category": "animal", "image_url": "🐟", "difficulty": 1},
        {"french": "chèvre", "shimaore": "mbouzi", "kibouchi": "", "category": "animal", "image_url": "🐐", "difficulty": 1},
        {"french": "moustique", "shimaore": "manundi", "kibouchi": "", "category": "animal", "image_url": "🦟", "difficulty": 1},
        {"french": "mouche", "shimaore": "ndzi", "kibouchi": "", "category": "animal", "image_url": "🪰", "difficulty": 1},
        {"french": "chauve-souris", "shimaore": "drema", "kibouchi": "", "category": "animal", "image_url": "🦇", "difficulty": 1},
        {"french": "serpent", "shimaore": "nyoha", "kibouchi": "", "category": "animal", "image_url": "🐍", "difficulty": 1},
        {"french": "lapin", "shimaore": "sungura", "kibouchi": "", "category": "animal", "image_url": "🐰", "difficulty": 1},
        {"french": "canard", "shimaore": "guisi", "kibouchi": "", "category": "animal", "image_url": "🦆", "difficulty": 1},
        {"french": "mouton", "shimaore": "baribari", "kibouchi": "", "category": "animal", "image_url": "🐑", "difficulty": 1},
        {"french": "crocodile", "shimaore": "vwai", "kibouchi": "", "category": "animal", "image_url": "🐊", "difficulty": 1},
        {"french": "caméléon", "shimaore": "tarundru", "kibouchi": "", "category": "animal", "image_url": "🦎", "difficulty": 1},
        {"french": "zébu", "shimaore": "nyombé", "kibouchi": "", "category": "animal", "image_url": "🐂", "difficulty": 1},
        {"french": "âne", "shimaore": "pundra", "kibouchi": "", "category": "animal", "image_url": "🫏", "difficulty": 1},

        # PAGE 3 - SUITE ANIMAUX
        {"french": "poule", "shimaore": "kouhou", "kibouchi": "", "category": "animal", "image_url": "🐔", "difficulty": 1},
        {"french": "pigeon", "shimaore": "ndiwa", "kibouchi": "", "category": "animal", "image_url": "🕊️", "difficulty": 1},
        {"french": "fourmis", "shimaore": "tsosso", "kibouchi": "", "category": "animal", "image_url": "🐜", "difficulty": 1},
        {"french": "chenille", "shimaore": "bazi", "kibouchi": "", "category": "animal", "image_url": "🐛", "difficulty": 1},
        {"french": "papillon", "shimaore": "pelapelaka", "kibouchi": "", "category": "animal", "image_url": "🦋", "difficulty": 1},
        {"french": "ver de terre", "shimaore": "lingoui lingoui", "kibouchi": "", "category": "animal", "image_url": "🪱", "difficulty": 1},
        {"french": "criquet", "shimaore": "furudji", "kibouchi": "", "category": "animal", "image_url": "🦗", "difficulty": 1},
        {"french": "cheval", "shimaore": "poundra", "kibouchi": "", "category": "animal", "image_url": "🐴", "difficulty": 1},
        {"french": "fruit du jaquier", "shimaore": "fénéssi", "kibouchi": "", "category": "vegetal", "image_url": "🥭", "difficulty": 1},
        {"french": "perroquet", "shimaore": "kasoukou", "kibouchi": "", "category": "animal", "image_url": "🦜", "difficulty": 1},
        {"french": "cafard", "shimaore": "kalalawi", "kibouchi": "", "category": "animal", "image_url": "🪳", "difficulty": 1},
        {"french": "araignée", "shimaore": "shitrandrabwibwi", "kibouchi": "", "category": "animal", "image_url": "🕷️", "difficulty": 1},
        {"french": "scorpion", "shimaore": "hala", "kibouchi": "", "category": "animal", "image_url": "🦂", "difficulty": 1},
        {"french": "scolopendre", "shimaore": "trambwi", "kibouchi": "", "category": "animal", "image_url": "🐛", "difficulty": 1},
        {"french": "thon", "shimaore": "mbassi", "kibouchi": "", "category": "animal", "image_url": "🐟", "difficulty": 1},
        {"french": "requin", "shimaore": "papa", "kibouchi": "", "category": "animal", "image_url": "🦈", "difficulty": 1},
        {"french": "poulpe", "shimaore": "pwedza", "kibouchi": "", "category": "animal", "image_url": "🐙", "difficulty": 1},
        {"french": "crabe", "shimaore": "dradraka", "kibouchi": "", "category": "animal", "image_url": "🦀", "difficulty": 1},
        {"french": "tortue", "shimaore": "nyamba/katsa", "kibouchi": "", "category": "animal", "image_url": "🐢", "difficulty": 1},
        {"french": "bigorno", "shimaore": "trondro", "kibouchi": "", "category": "animal", "image_url": "🐚", "difficulty": 1},
        {"french": "éléphant", "shimaore": "ndovu", "kibouchi": "", "category": "animal", "image_url": "🐘", "difficulty": 1},
        {"french": "lézard", "shimaore": "djakwe", "kibouchi": "", "category": "animal", "image_url": "🦎", "difficulty": 1},
        {"french": "renard", "shimaore": "shikwetse", "kibouchi": "", "category": "animal", "image_url": "🦊", "difficulty": 1},
        {"french": "singe", "shimaore": "pouruku nyeha", "kibouchi": "", "category": "animal", "image_url": "🐒", "difficulty": 1},
        {"french": "souris", "shimaore": "ngwizi", "kibouchi": "", "category": "animal", "image_url": "🐭", "difficulty": 1},
        {"french": "phacochère", "shimaore": "mbwa nyeha", "kibouchi": "", "category": "animal", "image_url": "🐗", "difficulty": 1},
        {"french": "chameau", "shimaore": "ngamia", "kibouchi": "", "category": "animal", "image_url": "🐪", "difficulty": 1},
        {"french": "escargot", "shimaore": "kowa", "kibouchi": "", "category": "animal", "image_url": "🐌", "difficulty": 1},
        {"french": "hérisson/tangue", "shimaore": "landra", "kibouchi": "", "category": "animal", "image_url": "🦔", "difficulty": 1},
        {"french": "corbeau", "shimaore": "gawa/kwayi", "kibouchi": "", "category": "animal", "image_url": "🐦‍⬛", "difficulty": 1},
        {"french": "civette", "shimaore": "founga", "kibouchi": "", "category": "animal", "image_url": "🦝", "difficulty": 1},
        {"french": "dauphin", "shimaore": "moungoumé", "kibouchi": "", "category": "animal", "image_url": "🐬", "difficulty": 1},
        {"french": "baleine", "shimaore": "ndroujou", "kibouchi": "", "category": "animal", "image_url": "🐋", "difficulty": 1},
        {"french": "crevette", "shimaore": "cambe", "kibouchi": "", "category": "animal", "image_url": "🦐", "difficulty": 1},
        {"french": "frelon", "shimaore": "chonga", "kibouchi": "", "category": "animal", "image_url": "🐝", "difficulty": 1},
        {"french": "guêpe", "shimaore": "movou", "kibouchi": "", "category": "animal", "image_url": "🐝", "difficulty": 1},
        {"french": "bourdon", "shimaore": "vungo vungo", "kibouchi": "", "category": "animal", "image_url": "🐝", "difficulty": 1},
        {"french": "puce", "shimaore": "kunguni", "kibouchi": "", "category": "animal", "image_url": "🐛", "difficulty": 1},
        {"french": "pou", "shimaore": "ndra", "kibouchi": "", "category": "animal", "image_url": "🐛", "difficulty": 1},
        {"french": "bouc", "shimaore": "béwé", "kibouchi": "", "category": "animal", "image_url": "🐐", "difficulty": 1},
        {"french": "taureau", "shimaore": "kondzo", "kibouchi": "", "category": "animal", "image_url": "🐂", "difficulty": 1},
        {"french": "bigorneau", "shimaore": "trondro", "kibouchi": "", "category": "animal", "image_url": "🐚", "difficulty": 1},
        {"french": "lambis", "shimaore": "kombé", "kibouchi": "", "category": "animal", "image_url": "🐚", "difficulty": 1},
        {"french": "cône de mer", "shimaore": "kwitsi", "kibouchi": "", "category": "animal", "image_url": "🐚", "difficulty": 1},
        {"french": "oursin", "shimaore": "gadzassi", "kibouchi": "", "category": "animal", "image_url": "🦔", "difficulty": 1},
        {"french": "huître", "shimaore": "gadzassi", "kibouchi": "", "category": "animal", "image_url": "🦪", "difficulty": 1},

        # PAGE 4 - CORPS HUMAIN ET SALUTATIONS
        {"french": "œil", "shimaore": "matso", "kibouchi": "", "category": "corps_humain", "image_url": "👁️", "difficulty": 1},
        {"french": "nez", "shimaore": "poua", "kibouchi": "", "category": "corps_humain", "image_url": "👃", "difficulty": 1},
        {"french": "oreille", "shimaore": "kiyo", "kibouchi": "", "category": "corps_humain", "image_url": "👂", "difficulty": 1},
        {"french": "ongle", "shimaore": "kofou", "kibouchi": "", "category": "corps_humain", "image_url": "💅", "difficulty": 1},
        {"french": "front", "shimaore": "housso", "kibouchi": "", "category": "corps_humain", "image_url": "🤔", "difficulty": 1},
        {"french": "joue", "shimaore": "savou", "kibouchi": "", "category": "corps_humain", "image_url": "😊", "difficulty": 1},
        {"french": "dos", "shimaore": "mengo", "kibouchi": "", "category": "corps_humain", "image_url": "🫸", "difficulty": 1},
        {"french": "épaule", "shimaore": "bèga", "kibouchi": "", "category": "corps_humain", "image_url": "💪", "difficulty": 1},
        {"french": "hanche", "shimaore": "trenga", "kibouchi": "", "category": "corps_humain", "image_url": "🫴", "difficulty": 1},
        {"french": "fesses", "shimaore": "shidzé/mvoumo", "kibouchi": "", "category": "corps_humain", "image_url": "🍑", "difficulty": 1},
        {"french": "main", "shimaore": "mhono", "kibouchi": "", "category": "corps_humain", "image_url": "✋", "difficulty": 1},
        {"french": "tête", "shimaore": "shitsoi", "kibouchi": "", "category": "corps_humain", "image_url": "🗣️", "difficulty": 1},
        {"french": "ventre", "shimaore": "mimba", "kibouchi": "", "category": "corps_humain", "image_url": "🤰", "difficulty": 1},
        {"french": "dent", "shimaore": "magno", "kibouchi": "", "category": "corps_humain", "image_url": "🦷", "difficulty": 1},
        {"french": "langue", "shimaore": "oulimé", "kibouchi": "", "category": "corps_humain", "image_url": "👅", "difficulty": 1},
        {"french": "pied", "shimaore": "mindrou", "kibouchi": "", "category": "corps_humain", "image_url": "🦶", "difficulty": 1},
        {"french": "lèvre", "shimaore": "dhomo", "kibouchi": "", "category": "corps_humain", "image_url": "👄", "difficulty": 1},
        {"french": "peau", "shimaore": "ngwezi", "kibouchi": "", "category": "corps_humain", "image_url": "🫱", "difficulty": 1},
        {"french": "cheveux", "shimaore": "ngnélé", "kibouchi": "", "category": "corps_humain", "image_url": "💇", "difficulty": 1},
        {"french": "doigts", "shimaore": "cha", "kibouchi": "", "category": "corps_humain", "image_url": "👆", "difficulty": 1},
        {"french": "barbe", "shimaore": "ndrévou", "kibouchi": "", "category": "corps_humain", "image_url": "🧔", "difficulty": 1},
        {"french": "vagin", "shimaore": "ndzigni", "kibouchi": "", "category": "corps_humain", "image_url": "🫦", "difficulty": 2},
        {"french": "testicules", "shimaore": "kwendzé", "kibouchi": "", "category": "corps_humain", "image_url": "🥎", "difficulty": 2},
        {"french": "pénis", "shimaore": "mbo", "kibouchi": "", "category": "corps_humain", "image_url": "🌶️", "difficulty": 2},
        {"french": "menton", "shimaore": "shlevo", "kibouchi": "", "category": "corps_humain", "image_url": "🫸", "difficulty": 1},
        {"french": "bouche", "shimaore": "hangno", "kibouchi": "", "category": "corps_humain", "image_url": "👄", "difficulty": 1},
        {"french": "côtes", "shimaore": "bavou", "kibouchi": "", "category": "corps_humain", "image_url": "🫁", "difficulty": 1},
        {"french": "sourcil", "shimaore": "tsi", "kibouchi": "", "category": "corps_humain", "image_url": "🤨", "difficulty": 1},
        {"french": "cheville", "shimaore": "dzitso la pwédza", "kibouchi": "", "category": "corps_humain", "image_url": "🦶", "difficulty": 1},
        {"french": "cou", "shimaore": "tsing", "kibouchi": "", "category": "corps_humain", "image_url": "🗣️", "difficulty": 1},
        {"french": "cils", "shimaore": "kovo", "kibouchi": "", "category": "corps_humain", "image_url": "👁️", "difficulty": 1},
        {"french": "arrière du crâne", "shimaore": "komoi", "kibouchi": "", "category": "corps_humain", "image_url": "🤯", "difficulty": 1},

        # SALUTATIONS - PAGE 4
        {"french": "bonjour", "shimaore": "kwezi", "kibouchi": "", "category": "salutations", "image_url": "☀️", "difficulty": 1},
        {"french": "comment ça va", "shimaore": "jéjé", "kibouchi": "", "category": "salutations", "image_url": "❓", "difficulty": 1},
        {"french": "oui", "shimaore": "ewa", "kibouchi": "", "category": "salutations", "image_url": "✅", "difficulty": 1},
        {"french": "non", "shimaore": "anha", "kibouchi": "", "category": "salutations", "image_url": "❌", "difficulty": 1},
        {"french": "ça va bien", "shimaore": "fétré", "kibouchi": "", "category": "salutations", "image_url": "😊", "difficulty": 1},
        {"french": "merci", "shimaore": "marahaba", "kibouchi": "", "category": "salutations", "image_url": "🙏", "difficulty": 1},
        {"french": "bonne nuit", "shimaore": "oukou wa hairi", "kibouchi": "", "category": "salutations", "image_url": "🌙", "difficulty": 1},
        {"french": "au revoir", "shimaore": "kwaheri", "kibouchi": "", "category": "salutations", "image_url": "👋", "difficulty": 1},

        # GRAMMAIRE - PAGE 4
        {"french": "je", "shimaore": "wami", "kibouchi": "", "category": "grammaire", "image_url": "👤", "difficulty": 1},
        {"french": "tu", "shimaore": "wawé", "kibouchi": "", "category": "grammaire", "image_url": "👤", "difficulty": 1},
        {"french": "il/elle", "shimaore": "wayé", "kibouchi": "", "category": "grammaire", "image_url": "👤", "difficulty": 1},
        {"french": "nous", "shimaore": "wassi", "kibouchi": "", "category": "grammaire", "image_url": "👥", "difficulty": 1},
        {"french": "ils/elles", "shimaore": "wawo", "kibouchi": "", "category": "grammaire", "image_url": "👥", "difficulty": 1},
        {"french": "le mien", "shimaore": "yangou", "kibouchi": "", "category": "grammaire", "image_url": "👤", "difficulty": 2},

        # PAGE 5 - SUITE GRAMMAIRE, PROFESSIONS, FAMILLE, COULEURS, DÉBUT NOURRITURE
        {"french": "le tien", "shimaore": "yaho", "kibouchi": "", "category": "grammaire", "image_url": "👤", "difficulty": 2},
        {"french": "le sien", "shimaore": "yahé", "kibouchi": "", "category": "grammaire", "image_url": "👤", "difficulty": 2},
        {"french": "le leur", "shimaore": "yawo", "kibouchi": "", "category": "grammaire", "image_url": "👥", "difficulty": 2},
        {"french": "le nôtre", "shimaore": "yatrou", "kibouchi": "", "category": "grammaire", "image_url": "👥", "difficulty": 2},
        {"french": "le vôtre", "shimaore": "yangnou", "kibouchi": "", "category": "grammaire", "image_url": "👥", "difficulty": 2},
        {"french": "vous", "shimaore": "wagnou", "kibouchi": "", "category": "grammaire", "image_url": "👥", "difficulty": 1},

        # PROFESSIONS - PAGE 5
        {"french": "professeur", "shimaore": "foundi", "kibouchi": "", "category": "profession", "image_url": "👨‍🏫", "difficulty": 1},
        {"french": "guide spirituel", "shimaore": "imam", "kibouchi": "", "category": "profession", "image_url": "👨‍🦲", "difficulty": 1},
        {"french": "voisin", "shimaore": "djirani", "kibouchi": "", "category": "profession", "image_url": "🏠", "difficulty": 1},
        {"french": "maire", "shimaore": "méra", "kibouchi": "", "category": "profession", "image_url": "🏛️", "difficulty": 1},
        {"french": "élu", "shimaore": "dhoimana", "kibouchi": "", "category": "profession", "image_url": "🗳️", "difficulty": 1},
        {"french": "pêcheur", "shimaore": "mlozi", "kibouchi": "", "category": "profession", "image_url": "🎣", "difficulty": 1},
        {"french": "agriculteur", "shimaore": "mlimizi", "kibouchi": "", "category": "profession", "image_url": "👨‍🌾", "difficulty": 1},
        {"french": "éleveur", "shimaore": "mtsounga", "kibouchi": "", "category": "profession", "image_url": "🐄", "difficulty": 1},

        # FAMILLE - PAGE 5
        {"french": "tante", "shimaore": "mama titi/bolé", "kibouchi": "", "category": "famille", "image_url": "👩", "difficulty": 1},
        {"french": "oncle maternel", "shimaore": "zama", "kibouchi": "", "category": "famille", "image_url": "👨", "difficulty": 2},
        {"french": "oncle paternel", "shimaore": "baba titi/bolé", "kibouchi": "", "category": "famille", "image_url": "👨", "difficulty": 2},
        {"french": "épouse oncle maternel", "shimaore": "zena", "kibouchi": "", "category": "famille", "image_url": "👩", "difficulty": 2},
        {"french": "petite sœur", "shimaore": "moinagna mtroumama", "kibouchi": "", "category": "famille", "image_url": "👧", "difficulty": 1},
        {"french": "petit frère", "shimaore": "moinagna mtroubaba", "kibouchi": "", "category": "famille", "image_url": "👦", "difficulty": 1},
        {"french": "grande sœur", "shimaore": "zouki mtroumché", "kibouchi": "", "category": "famille", "image_url": "👩", "difficulty": 1},
        {"french": "grand frère", "shimaore": "zouki mtoubaba", "kibouchi": "", "category": "famille", "image_url": "👨", "difficulty": 1},
        {"french": "frère", "shimaore": "mwanagna mtroubaba", "kibouchi": "", "category": "famille", "image_url": "👦", "difficulty": 1},
        {"french": "sœur", "shimaore": "mwanagna mtroumama", "kibouchi": "", "category": "famille", "image_url": "👧", "difficulty": 1},
        {"french": "ami", "shimaore": "mwandzani", "kibouchi": "", "category": "famille", "image_url": "👫", "difficulty": 1},
        {"french": "fille/femme", "shimaore": "mtroumama", "kibouchi": "", "category": "famille", "image_url": "👩", "difficulty": 1},
        {"french": "garçon/homme", "shimaore": "mtroubaba", "kibouchi": "", "category": "famille", "image_url": "👨", "difficulty": 1},
        {"french": "monsieur", "shimaore": "mogné", "kibouchi": "", "category": "famille", "image_url": "👨", "difficulty": 1},
        {"french": "grand-père", "shimaore": "bacoco", "kibouchi": "", "category": "famille", "image_url": "👴", "difficulty": 1},
        {"french": "grand-mère", "shimaore": "coco", "kibouchi": "", "category": "famille", "image_url": "👵", "difficulty": 1},
        {"french": "madame", "shimaore": "bwéni", "kibouchi": "", "category": "famille", "image_url": "👩", "difficulty": 1},
        {"french": "famille", "shimaore": "mdjamaza", "kibouchi": "", "category": "famille", "image_url": "👨‍👩‍👧‍👦", "difficulty": 1},
        {"french": "papa", "shimaore": "baba", "kibouchi": "", "category": "famille", "image_url": "👨", "difficulty": 1},
        {"french": "maman", "shimaore": "mama", "kibouchi": "", "category": "famille", "image_url": "👩", "difficulty": 1},

        # COULEURS - PAGE 5
        {"french": "bleu", "shimaore": "bilé", "kibouchi": "", "category": "couleur", "image_url": "🔵", "difficulty": 1},
        {"french": "vert", "shimaore": "dhavou", "kibouchi": "", "category": "couleur", "image_url": "🟢", "difficulty": 1},
        {"french": "noir", "shimaore": "nzidhou", "kibouchi": "", "category": "couleur", "image_url": "⚫", "difficulty": 1},
        {"french": "blanc", "shimaore": "ndjéou", "kibouchi": "", "category": "couleur", "image_url": "⚪", "difficulty": 1},
        {"french": "jaune", "shimaore": "dzindzano", "kibouchi": "", "category": "couleur", "image_url": "🟡", "difficulty": 1},
        {"french": "rouge", "shimaore": "nzoukoundrou", "kibouchi": "", "category": "couleur", "image_url": "🔴", "difficulty": 1},
        {"french": "gris", "shimaore": "djifou", "kibouchi": "", "category": "couleur", "image_url": "⚫", "difficulty": 1},
        {"french": "marron", "shimaore": "trotro", "kibouchi": "", "category": "couleur", "image_url": "🟤", "difficulty": 1},

        # DÉBUT NOURRITURE - PAGE 5
        {"french": "riz", "shimaore": "tsoholé", "kibouchi": "", "category": "nourriture", "image_url": "🍚", "difficulty": 1},
        {"french": "eau", "shimaore": "maji", "kibouchi": "", "category": "nourriture", "image_url": "💧", "difficulty": 1},

        # PAGE 6 - SUITE NOURRITURE ET MAISON
        {"french": "ananas", "shimaore": "nanassi", "kibouchi": "", "category": "nourriture", "image_url": "🍍", "difficulty": 1},
        {"french": "pois d'angole", "shimaore": "tsouzi", "kibouchi": "", "category": "nourriture", "image_url": "🫘", "difficulty": 1},
        {"french": "banane", "shimaore": "trovi", "kibouchi": "", "category": "nourriture", "image_url": "🍌", "difficulty": 1},
        {"french": "pain", "shimaore": "dipé", "kibouchi": "", "category": "nourriture", "image_url": "🍞", "difficulty": 1},
        {"french": "gâteau", "shimaore": "mharé", "kibouchi": "", "category": "nourriture", "image_url": "🍰", "difficulty": 1},
        {"french": "mangue", "shimaore": "manga", "kibouchi": "", "category": "nourriture", "image_url": "🥭", "difficulty": 1},
        {"french": "noix de coco", "shimaore": "nadzi", "kibouchi": "", "category": "nourriture", "image_url": "🥥", "difficulty": 1},
        {"french": "noix de coco fraîche", "shimaore": "chijavou", "kibouchi": "", "category": "nourriture", "image_url": "🥥", "difficulty": 1},
        {"french": "lait", "shimaore": "dzia", "kibouchi": "", "category": "nourriture", "image_url": "🥛", "difficulty": 1},
        {"french": "viande", "shimaore": "nhyama", "kibouchi": "", "category": "nourriture", "image_url": "🥩", "difficulty": 1},
        {"french": "poisson", "shimaore": "fi", "kibouchi": "", "category": "nourriture", "image_url": "🐟", "difficulty": 1},
        {"french": "brèdes", "shimaore": "féliki", "kibouchi": "", "category": "nourriture", "image_url": "🥬", "difficulty": 1},
        {"french": "brède mafane", "shimaore": "féliki mafana", "kibouchi": "", "category": "nourriture", "image_url": "🥬", "difficulty": 1},
        {"french": "brède manioc", "shimaore": "féliki nyongo", "kibouchi": "", "category": "nourriture", "image_url": "🥬", "difficulty": 1},
        {"french": "brède morelle", "shimaore": "féliki batata", "kibouchi": "", "category": "nourriture", "image_url": "🥬", "difficulty": 1},
        {"french": "brèdes patate douce", "shimaore": "batata", "kibouchi": "", "category": "nourriture", "image_url": "🍠", "difficulty": 1},
        {"french": "patate douce", "shimaore": "batata", "kibouchi": "", "category": "nourriture", "image_url": "🍠", "difficulty": 1},
        {"french": "bouillon", "shimaore": "woubou", "kibouchi": "", "category": "nourriture", "image_url": "🍲", "difficulty": 1},
        {"french": "banane au coco", "shimaore": "trovi ya nadzi", "kibouchi": "", "category": "nourriture", "image_url": "🍌", "difficulty": 1},
        {"french": "riz au coco", "shimaore": "tsoholé ya nadzi", "kibouchi": "", "category": "nourriture", "image_url": "🍚", "difficulty": 1},
        {"french": "poulet", "shimaore": "bawa", "kibouchi": "", "category": "nourriture", "image_url": "🐔", "difficulty": 1},
        {"french": "œuf", "shimaore": "joiyi", "kibouchi": "", "category": "nourriture", "image_url": "🥚", "difficulty": 1},
        {"french": "tomate", "shimaore": "tamati", "kibouchi": "", "category": "nourriture", "image_url": "🍅", "difficulty": 1},
        {"french": "oignon", "shimaore": "chouroungou", "kibouchi": "", "category": "nourriture", "image_url": "🧅", "difficulty": 1},
        {"french": "ail", "shimaore": "chouroungou foudjé", "kibouchi": "", "category": "nourriture", "image_url": "🧄", "difficulty": 1},
        {"french": "orange", "shimaore": "troundra", "kibouchi": "", "category": "nourriture", "image_url": "🍊", "difficulty": 1},
        {"french": "mandarine", "shimaore": "madhandzé", "kibouchi": "", "category": "nourriture", "image_url": "🍊", "difficulty": 1},
        {"french": "manioc", "shimaore": "mhogo", "kibouchi": "", "category": "nourriture", "image_url": "🥔", "difficulty": 1},
        {"french": "piment", "shimaore": "poutou", "kibouchi": "", "category": "nourriture", "image_url": "🌶️", "difficulty": 1},
        {"french": "taro", "shimaore": "majimbi", "kibouchi": "", "category": "nourriture", "image_url": "🥔", "difficulty": 1},
        {"french": "sel", "shimaore": "ching", "kibouchi": "", "category": "nourriture", "image_url": "🧂", "difficulty": 1},
        {"french": "poivre", "shimaore": "bvilibvili manga", "kibouchi": "", "category": "nourriture", "image_url": "🌶️", "difficulty": 1},
        {"french": "curcuma", "shimaore": "dzindzano", "kibouchi": "", "category": "nourriture", "image_url": "🌿", "difficulty": 1},
        {"french": "cumin", "shimaore": "massala", "kibouchi": "", "category": "nourriture", "image_url": "🌿", "difficulty": 1},
        {"french": "ciboulette", "shimaore": "chourougnou", "kibouchi": "", "category": "nourriture", "image_url": "🌿", "difficulty": 1},
        {"french": "gingembre", "shimaore": "tsingiziou", "kibouchi": "", "category": "nourriture", "image_url": "🫚", "difficulty": 1},
        {"french": "vanille", "shimaore": "lavani", "kibouchi": "", "category": "nourriture", "image_url": "🌿", "difficulty": 1},
        {"french": "tamarin", "shimaore": "ouhajou", "kibouchi": "", "category": "nourriture", "image_url": "🌰", "difficulty": 1},
        {"french": "thé", "shimaore": "maji ya moro", "kibouchi": "", "category": "nourriture", "image_url": "🍵", "difficulty": 1},
        {"french": "papaye", "shimaore": "papaya", "kibouchi": "", "category": "nourriture", "image_url": "🥭", "difficulty": 1},
        {"french": "riz non décortiqué", "shimaore": "chaoula", "kibouchi": "", "category": "nourriture", "image_url": "🌾", "difficulty": 1},

        # MAISON - PAGE 6
        {"french": "maison", "shimaore": "nyoumba", "kibouchi": "", "category": "maison", "image_url": "🏠", "difficulty": 1},
        {"french": "porte", "shimaore": "mlango", "kibouchi": "", "category": "maison", "image_url": "🚪", "difficulty": 1},
        {"french": "case", "shimaore": "banga", "kibouchi": "", "category": "maison", "image_url": "🏠", "difficulty": 1},

        # PAGE 7 - OBJETS
        {"french": "lit", "shimaore": "chtrandra", "kibouchi": "", "category": "objet", "image_url": "🛏️", "difficulty": 1},
        {"french": "marmite", "shimaore": "gnougou", "kibouchi": "", "category": "objet", "image_url": "🍲", "difficulty": 1},
        {"french": "vaisselle", "shimaore": "ziya", "kibouchi": "", "category": "objet", "image_url": "🍽️", "difficulty": 1},
        {"french": "bol", "shimaore": "chicombé", "kibouchi": "", "category": "objet", "image_url": "🥣", "difficulty": 1},
        {"french": "soutrou", "shimaore": "soutrou", "kibouchi": "", "category": "objet", "image_url": "🥄", "difficulty": 1},
        {"french": "cuillère", "shimaore": "chiri", "kibouchi": "", "category": "objet", "image_url": "🥄", "difficulty": 1},
        {"french": "fenêtre", "shimaore": "fénétri", "kibouchi": "", "category": "objet", "image_url": "🪟", "difficulty": 1},
        {"french": "chaise", "shimaore": "latabou", "kibouchi": "", "category": "objet", "image_url": "🪑", "difficulty": 1},
        {"french": "table", "shimaore": "chido", "kibouchi": "", "category": "objet", "image_url": "🪑", "difficulty": 1},
        {"french": "miroir", "shimaore": "mraba", "kibouchi": "", "category": "objet", "image_url": "🪞", "difficulty": 1},
        {"french": "cour", "shimaore": "vala", "kibouchi": "", "category": "objet", "image_url": "🏡", "difficulty": 1},
        {"french": "clôture", "shimaore": "mrabani", "kibouchi": "", "category": "objet", "image_url": "🚧", "difficulty": 1},
        {"french": "toilette", "shimaore": "siyo", "kibouchi": "", "category": "objet", "image_url": "🚽", "difficulty": 1},
        {"french": "seau", "shimaore": "paou", "kibouchi": "", "category": "objet", "image_url": "🪣", "difficulty": 1},
        {"french": "louche", "shimaore": "sembéya", "kibouchi": "", "category": "objet", "image_url": "🥄", "difficulty": 1},
        {"french": "couteau", "shimaore": "godoro", "kibouchi": "", "category": "objet", "image_url": "🔪", "difficulty": 1},
        {"french": "matelas", "shimaore": "mtsao", "kibouchi": "", "category": "objet", "image_url": "🛏️", "difficulty": 1},
        {"french": "oreiller", "shimaore": "biffé", "kibouchi": "", "category": "objet", "image_url": "🛌", "difficulty": 1},
        {"french": "buffet", "shimaore": "péssi", "kibouchi": "", "category": "objet", "image_url": "🗄️", "difficulty": 1},
        {"french": "mur", "shimaore": "baraza", "kibouchi": "", "category": "objet", "image_url": "🧱", "difficulty": 1},
        {"french": "véranda", "shimaore": "outro", "kibouchi": "", "category": "objet", "image_url": "🏠", "difficulty": 1},
        {"french": "toiture", "shimaore": "lalampou", "kibouchi": "", "category": "objet", "image_url": "🏠", "difficulty": 1},
        {"french": "ampoule", "shimaore": "mwengué", "kibouchi": "", "category": "objet", "image_url": "💡", "difficulty": 1},
        {"french": "lumière", "shimaore": "pongé", "kibouchi": "", "category": "objet", "image_url": "💡", "difficulty": 1},
        {"french": "torche", "shimaore": "soha", "kibouchi": "", "category": "objet", "image_url": "🔦", "difficulty": 1},
        {"french": "hache", "shimaore": "m'panga", "kibouchi": "", "category": "objet", "image_url": "🪓", "difficulty": 1},
        {"french": "machette", "shimaore": "chombo", "kibouchi": "", "category": "objet", "image_url": "🗡️", "difficulty": 1},
        {"french": "coupe-coupe", "shimaore": "mkoba", "kibouchi": "", "category": "objet", "image_url": "🗡️", "difficulty": 1},
        {"french": "sac", "shimaore": "gouni", "kibouchi": "", "category": "objet", "image_url": "🎒", "difficulty": 1},
        {"french": "balai", "shimaore": "péou", "kibouchi": "", "category": "objet", "image_url": "🧹", "difficulty": 1},
        {"french": "mortier", "shimaore": "chino", "kibouchi": "", "category": "objet", "image_url": "🫖", "difficulty": 1},
        {"french": "assiette", "shimaore": "sahani", "kibouchi": "", "category": "objet", "image_url": "🍽️", "difficulty": 1},
        {"french": "fondation", "shimaore": "houra", "kibouchi": "", "category": "objet", "image_url": "🏗️", "difficulty": 1},
        {"french": "torche locale", "shimaore": "gandilé/poutroumax", "kibouchi": "", "category": "objet", "image_url": "🔦", "difficulty": 1},

        # VERBES - DÉBUT PAGE 7
        {"french": "jouer", "shimaore": "ounguadza", "kibouchi": "", "category": "verbe", "image_url": "⚽", "difficulty": 1},
        {"french": "courir", "shimaore": "wendra mbiyo", "kibouchi": "", "category": "verbe", "image_url": "🏃", "difficulty": 1},
        {"french": "dire", "shimaore": "ourongoa", "kibouchi": "", "category": "verbe", "image_url": "🗣️", "difficulty": 1},
        {"french": "pouvoir", "shimaore": "ouchindra", "kibouchi": "", "category": "verbe", "image_url": "💪", "difficulty": 1},
        {"french": "vouloir", "shimaore": "outsaha", "kibouchi": "", "category": "verbe", "image_url": "🤲", "difficulty": 1},
        {"french": "savoir", "shimaore": "oujoua", "kibouchi": "", "category": "verbe", "image_url": "🧠", "difficulty": 1},
        {"french": "voir", "shimaore": "ouona", "kibouchi": "", "category": "verbe", "image_url": "👁️", "difficulty": 1},
        {"french": "devoir", "shimaore": "oulazimou", "kibouchi": "", "category": "verbe", "image_url": "⚖️", "difficulty": 1},
        {"french": "venir", "shimaore": "ouja", "kibouchi": "", "category": "verbe", "image_url": "🏃", "difficulty": 1},
        {"french": "rapprocher", "shimaore": "outsenguéléya", "kibouchi": "", "category": "verbe", "image_url": "👥", "difficulty": 1},

        # PAGE 8 - SUITE VERBES
        {"french": "prendre", "shimaore": "ourenga", "kibouchi": "", "category": "verbe", "image_url": "✋", "difficulty": 1},
        {"french": "donner", "shimaore": "ouva", "kibouchi": "", "category": "verbe", "image_url": "🤲", "difficulty": 1},
        {"french": "parler", "shimaore": "oulagoua", "kibouchi": "", "category": "verbe", "image_url": "🗣️", "difficulty": 1},
        {"french": "mettre", "shimaore": "outria", "kibouchi": "", "category": "verbe", "image_url": "👆", "difficulty": 1},
        {"french": "passer", "shimaore": "ouvira", "kibouchi": "", "category": "verbe", "image_url": "🚶", "difficulty": 1},
        {"french": "trouver", "shimaore": "oupara", "kibouchi": "", "category": "verbe", "image_url": "🔍", "difficulty": 1},
        {"french": "aimer", "shimaore": "ouvendza", "kibouchi": "", "category": "verbe", "image_url": "❤️", "difficulty": 1},
        {"french": "croire", "shimaore": "ouamini", "kibouchi": "", "category": "verbe", "image_url": "🙏", "difficulty": 1},
        {"french": "penser", "shimaore": "oufikiri", "kibouchi": "", "category": "verbe", "image_url": "🤔", "difficulty": 1},
        {"french": "connaître", "shimaore": "oujoua", "kibouchi": "", "category": "verbe", "image_url": "🧠", "difficulty": 1},
        {"french": "demander", "shimaore": "oudzissa", "kibouchi": "", "category": "verbe", "image_url": "❓", "difficulty": 1},
        {"french": "répondre", "shimaore": "oudjibou", "kibouchi": "", "category": "verbe", "image_url": "💬", "difficulty": 1},
        {"french": "laisser", "shimaore": "oulicha", "kibouchi": "", "category": "verbe", "image_url": "👋", "difficulty": 1},
        {"french": "manger", "shimaore": "oudhya", "kibouchi": "", "category": "verbe", "image_url": "🍽️", "difficulty": 1},
        {"french": "boire", "shimaore": "ounoua", "kibouchi": "", "category": "verbe", "image_url": "🥤", "difficulty": 1},
        {"french": "lire", "shimaore": "ousoma", "kibouchi": "", "category": "verbe", "image_url": "📖", "difficulty": 1},
        {"french": "écrire", "shimaore": "ouhanguiha", "kibouchi": "", "category": "verbe", "image_url": "✍️", "difficulty": 1},
        {"french": "écouter", "shimaore": "ouvoulikia", "kibouchi": "", "category": "verbe", "image_url": "👂", "difficulty": 1},
        {"french": "apprendre", "shimaore": "oufoundriha", "kibouchi": "", "category": "verbe", "image_url": "📚", "difficulty": 1},
        {"french": "comprendre", "shimaore": "ouéléwa", "kibouchi": "", "category": "verbe", "image_url": "💡", "difficulty": 1},
        {"french": "jouer", "shimaore": "oungadza", "kibouchi": "", "category": "verbe", "image_url": "⚽", "difficulty": 1},
        {"french": "marcher", "shimaore": "ouendra", "kibouchi": "", "category": "verbe", "image_url": "🚶", "difficulty": 1},
        {"french": "entrer", "shimaore": "ounguiya", "kibouchi": "", "category": "verbe", "image_url": "🚪", "difficulty": 1},
        {"french": "sortir", "shimaore": "oulawa", "kibouchi": "", "category": "verbe", "image_url": "🚪", "difficulty": 1},
        {"french": "rester", "shimaore": "ouketi", "kibouchi": "", "category": "verbe", "image_url": "🏠", "difficulty": 1},
        {"french": "vivre", "shimaore": "oulala", "kibouchi": "", "category": "verbe", "image_url": "❤️", "difficulty": 1},
        {"french": "dormir", "shimaore": "oulindra", "kibouchi": "", "category": "verbe", "image_url": "😴", "difficulty": 1},
        {"french": "attendre", "shimaore": "oulindra", "kibouchi": "", "category": "verbe", "image_url": "⏰", "difficulty": 1},
        {"french": "suivre", "shimaore": "oulonga", "kibouchi": "", "category": "verbe", "image_url": "👥", "difficulty": 1},
        {"french": "tenir", "shimaore": "oussika", "kibouchi": "", "category": "verbe", "image_url": "✋", "difficulty": 1},
        {"french": "ouvrir", "shimaore": "ouboua", "kibouchi": "", "category": "verbe", "image_url": "🔓", "difficulty": 1},
        {"french": "fermer", "shimaore": "oubala", "kibouchi": "", "category": "verbe", "image_url": "🔒", "difficulty": 1},
        {"french": "sembler", "shimaore": "oufana", "kibouchi": "", "category": "verbe", "image_url": "🤔", "difficulty": 1},
        {"french": "paraître", "shimaore": "ouwonehoua", "kibouchi": "", "category": "verbe", "image_url": "👁️", "difficulty": 1},
        {"french": "devenir", "shimaore": "ougawouha", "kibouchi": "", "category": "verbe", "image_url": "🔄", "difficulty": 1},
        {"french": "tomber", "shimaore": "oupouliha", "kibouchi": "", "category": "verbe", "image_url": "⬇️", "difficulty": 1},
        {"french": "se rappeler", "shimaore": "oumaézi", "kibouchi": "", "category": "verbe", "image_url": "🧠", "difficulty": 1},
        {"french": "commencer", "shimaore": "ouhandrissa", "kibouchi": "", "category": "verbe", "image_url": "▶️", "difficulty": 1},
        {"french": "finir", "shimaore": "oumalidza", "kibouchi": "", "category": "verbe", "image_url": "✅", "difficulty": 1},
        {"french": "réussir", "shimaore": "ouchindra", "kibouchi": "", "category": "verbe", "image_url": "🏆", "difficulty": 1},
        {"french": "essayer", "shimaore": "oudjérébou", "kibouchi": "", "category": "verbe", "image_url": "🤞", "difficulty": 1},
        {"french": "attraper", "shimaore": "oubara", "kibouchi": "", "category": "verbe", "image_url": "✋", "difficulty": 1},
        {"french": "flatuler", "shimaore": "oujamba", "kibouchi": "", "category": "verbe", "image_url": "💨", "difficulty": 1},
        {"french": "traverser", "shimaore": "ouchiya", "kibouchi": "", "category": "verbe", "image_url": "🚶", "difficulty": 1},
        {"french": "sauter", "shimaore": "ouarouka", "kibouchi": "", "category": "verbe", "image_url": "🦘", "difficulty": 1},
        {"french": "frapper", "shimaore": "ourema", "kibouchi": "", "category": "verbe", "image_url": "👊", "difficulty": 1},
        {"french": "faire caca", "shimaore": "ougna madzi", "kibouchi": "", "category": "verbe", "image_url": "💩", "difficulty": 1},
        {"french": "faire pipi", "shimaore": "ougna kojo", "kibouchi": "", "category": "verbe", "image_url": "💧", "difficulty": 1},
        {"french": "vomir", "shimaore": "ouraviha", "kibouchi": "", "category": "verbe", "image_url": "🤮", "difficulty": 1},
        {"french": "s'asseoir", "shimaore": "ouketi", "kibouchi": "", "category": "verbe", "image_url": "🪑", "difficulty": 1},

        # PAGE 9 - SUITE VERBES
        {"french": "danser", "shimaore": "ouzina", "kibouchi": "", "category": "verbe", "image_url": "💃", "difficulty": 1},
        {"french": "arrêter", "shimaore": "ouziya", "kibouchi": "", "category": "verbe", "image_url": "🛑", "difficulty": 1},
        {"french": "vendre", "shimaore": "ouhoudza", "kibouchi": "", "category": "verbe", "image_url": "💰", "difficulty": 1},
        {"french": "cracher", "shimaore": "otra marré", "kibouchi": "", "category": "verbe", "image_url": "💦", "difficulty": 1},
        {"french": "mordre", "shimaore": "ouka magno", "kibouchi": "", "category": "verbe", "image_url": "🦷", "difficulty": 1},
        {"french": "gratter", "shimaore": "oukouwa", "kibouchi": "", "category": "verbe", "image_url": "✋", "difficulty": 1},
        {"french": "embrasser", "shimaore": "ounouka", "kibouchi": "", "category": "verbe", "image_url": "💋", "difficulty": 1},
        {"french": "jeter", "shimaore": "ouvoutsa", "kibouchi": "", "category": "verbe", "image_url": "🗑️", "difficulty": 1},
        {"french": "avertir", "shimaore": "outahadaricha", "kibouchi": "", "category": "verbe", "image_url": "⚠️", "difficulty": 1},
        {"french": "informer", "shimaore": "oujoudza", "kibouchi": "", "category": "verbe", "image_url": "📢", "difficulty": 1},
        {"french": "se laver le derrière", "shimaore": "outsamba", "kibouchi": "", "category": "verbe", "image_url": "🚿", "difficulty": 1},
        {"french": "se laver", "shimaore": "ouhowa", "kibouchi": "", "category": "verbe", "image_url": "🧼", "difficulty": 1},
        {"french": "piler", "shimaore": "oudoudoua", "kibouchi": "", "category": "verbe", "image_url": "🔨", "difficulty": 1},
        {"french": "changer", "shimaore": "ougaoudza", "kibouchi": "", "category": "verbe", "image_url": "🔄", "difficulty": 1},
        {"french": "étendre au soleil", "shimaore": "ouaniha", "kibouchi": "", "category": "verbe", "image_url": "☀️", "difficulty": 1},
        {"french": "réchauffer", "shimaore": "ouhelesedza", "kibouchi": "", "category": "verbe", "image_url": "🔥", "difficulty": 1},
        {"french": "se baigner", "shimaore": "ouhowa", "kibouchi": "", "category": "verbe", "image_url": "🏊", "difficulty": 1},
        {"french": "faire le lit", "shimaore": "ouhodza", "kibouchi": "", "category": "verbe", "image_url": "🛏️", "difficulty": 1},
        {"french": "faire sécher", "shimaore": "ouhoumisa", "kibouchi": "", "category": "verbe", "image_url": "🌞", "difficulty": 1},
        {"french": "balayer", "shimaore": "ouhoundza", "kibouchi": "", "category": "verbe", "image_url": "🧹", "difficulty": 1},
        {"french": "couper", "shimaore": "ouka", "kibouchi": "", "category": "verbe", "image_url": "✂️", "difficulty": 1},
        {"french": "tremper", "shimaore": "olodza", "kibouchi": "", "category": "verbe", "image_url": "💧", "difficulty": 1},
        {"french": "se raser", "shimaore": "oumea ndrevu", "kibouchi": "", "category": "verbe", "image_url": "🪒", "difficulty": 1},
        {"french": "abîmer", "shimaore": "oumengna", "kibouchi": "", "category": "verbe", "image_url": "💥", "difficulty": 1},
        {"french": "entrer", "shimaore": "ounguiya", "kibouchi": "", "category": "verbe", "image_url": "🚪", "difficulty": 1},
        {"french": "acheter", "shimaore": "ounnounoua", "kibouchi": "", "category": "verbe", "image_url": "🛒", "difficulty": 1},
        {"french": "griller", "shimaore": "ouwoha", "kibouchi": "", "category": "verbe", "image_url": "🔥", "difficulty": 1},
        {"french": "allumer", "shimaore": "oupatsa", "kibouchi": "", "category": "verbe", "image_url": "🔥", "difficulty": 1},
        {"french": "se peigner", "shimaore": "oupengné", "kibouchi": "", "category": "verbe", "image_url": "💇", "difficulty": 1},
        {"french": "cuisiner", "shimaore": "oupiha", "kibouchi": "", "category": "verbe", "image_url": "👩‍🍳", "difficulty": 1},
        {"french": "tresser", "shimaore": "ourenguélédza", "kibouchi": "", "category": "verbe", "image_url": "💇", "difficulty": 1},
        {"french": "peindre", "shimaore": "oussouka", "kibouchi": "", "category": "verbe", "image_url": "🎨", "difficulty": 1},
        {"french": "ranger/arranger", "shimaore": "ouvangouha", "kibouchi": "", "category": "verbe", "image_url": "📦", "difficulty": 1},
        {"french": "essuyer", "shimaore": "ouvangouha", "kibouchi": "", "category": "verbe", "image_url": "🧽", "difficulty": 1},
        {"french": "amener/apporter", "shimaore": "ouvinga", "kibouchi": "", "category": "verbe", "image_url": "🤲", "difficulty": 1},
        {"french": "éteindre", "shimaore": "ouzima", "kibouchi": "", "category": "verbe", "image_url": "🌫️", "difficulty": 1},
        {"french": "tuer", "shimaore": "ouwoula", "kibouchi": "", "category": "verbe", "image_url": "💀", "difficulty": 1},
        {"french": "combler", "shimaore": "oufitsiya", "kibouchi": "", "category": "verbe", "image_url": "⬆️", "difficulty": 1},
        {"french": "cultiver", "shimaore": "oulima", "kibouchi": "", "category": "verbe", "image_url": "🌱", "difficulty": 1},
        {"french": "couper du bois", "shimaore": "oupasouha kuni", "kibouchi": "", "category": "verbe", "image_url": "🪓", "difficulty": 1},
        {"french": "cueillir", "shimaore": "oupoua", "kibouchi": "", "category": "verbe", "image_url": "🌸", "difficulty": 1},
        {"french": "planter", "shimaore": "outabou", "kibouchi": "", "category": "verbe", "image_url": "🌱", "difficulty": 1},
        {"french": "creuser", "shimaore": "outsimba", "kibouchi": "", "category": "verbe", "image_url": "⛏️", "difficulty": 1},
        {"french": "récolter", "shimaore": "ouvouna", "kibouchi": "", "category": "verbe", "image_url": "🌾", "difficulty": 1},
        {"french": "bouger", "shimaore": "outsenguéléya", "kibouchi": "", "category": "verbe", "image_url": "🏃", "difficulty": 1},
        {"french": "arnaquer", "shimaore": "ourayi", "kibouchi": "", "category": "verbe", "image_url": "🤥", "difficulty": 1},

        # PAGE 10 - EXPRESSIONS
        {"french": "excuse-moi/pardon", "shimaore": "soimahani", "kibouchi": "", "category": "expression", "image_url": "🙏", "difficulty": 1},
        {"french": "j'ai faim", "shimaore": "nissi ona ndza", "kibouchi": "", "category": "expression", "image_url": "🍽️", "difficulty": 1},
        {"french": "j'ai soif", "shimaore": "nissi ona niyora", "kibouchi": "", "category": "expression", "image_url": "💧", "difficulty": 1},
        {"french": "je voudrais aller à", "shimaore": "nissi tsaha nendré", "kibouchi": "", "category": "expression", "image_url": "🚶", "difficulty": 1},
        {"french": "j'arrive de", "shimaore": "tsi lawa", "kibouchi": "", "category": "expression", "image_url": "🏃", "difficulty": 1},
        {"french": "je peux avoir des toilettes", "shimaore": "tnissi miya mraba", "kibouchi": "", "category": "expression", "image_url": "🚽", "difficulty": 1},
        {"french": "je veux manger", "shimaore": "nissi miya chaoula", "kibouchi": "", "category": "expression", "image_url": "🍽️", "difficulty": 1},
        {"french": "où se trouve", "shimaore": "ouparihanoua havi", "kibouchi": "", "category": "expression", "image_url": "📍", "difficulty": 1},
        {"french": "où sommes-nous", "shimaore": "ra havi", "kibouchi": "", "category": "expression", "image_url": "📍", "difficulty": 1},
        {"french": "je suis perdu", "shimaore": "tsi latsiha", "kibouchi": "", "category": "expression", "image_url": "🤷", "difficulty": 1},
        {"french": "bienvenu", "shimaore": "oukaribissa", "kibouchi": "", "category": "expression", "image_url": "🤗", "difficulty": 1},
        {"french": "je t'aime", "shimaore": "nisouhou vendza", "kibouchi": "", "category": "expression", "image_url": "❤️", "difficulty": 1},
        {"french": "j'ai mal", "shimaore": "nissi kodza", "kibouchi": "", "category": "expression", "image_url": "😵", "difficulty": 1},
        {"french": "pouvez-vous m'aider ?", "shimaore": "ni sayidié vanou", "kibouchi": "", "category": "expression", "image_url": "🤝", "difficulty": 1},
        {"french": "j'ai compris", "shimaore": "tsi héléwa", "kibouchi": "", "category": "expression", "image_url": "💡", "difficulty": 1},
        {"french": "je ne peux pas", "shimaore": "tsi chindri", "kibouchi": "", "category": "expression", "image_url": "🚫", "difficulty": 1},
        {"french": "montre-moi", "shimaore": "néssédzéyé", "kibouchi": "", "category": "expression", "image_url": "👁️", "difficulty": 1},
        {"french": "s'il vous plaît", "shimaore": "tafadali", "kibouchi": "", "category": "expression", "image_url": "🙏", "difficulty": 1},
        {"french": "combien ça coûte ?", "shimaore": "kissajé", "kibouchi": "", "category": "expression", "image_url": "💰", "difficulty": 1},
        {"french": "à gauche", "shimaore": "potroni", "kibouchi": "", "category": "expression", "image_url": "⬅️", "difficulty": 1},
        {"french": "à droite", "shimaore": "houméni", "kibouchi": "", "category": "expression", "image_url": "➡️", "difficulty": 1},
        {"french": "tout droit", "shimaore": "hondzoha", "kibouchi": "", "category": "expression", "image_url": "⬆️", "difficulty": 1},
        {"french": "c'est loin ?", "shimaore": "ya mbali", "kibouchi": "", "category": "expression", "image_url": "📏", "difficulty": 1},
        {"french": "c'est très bon !", "shimaore": "issi jiva", "kibouchi": "", "category": "expression", "image_url": "😋", "difficulty": 1},
        {"french": "trop cher", "shimaore": "hali", "kibouchi": "", "category": "expression", "image_url": "💸", "difficulty": 1},
        {"french": "moins cher s'il vous plaît", "shimaore": "nissi miya ouchoukidzé", "kibouchi": "", "category": "expression", "image_url": "💰", "difficulty": 1},
        {"french": "je prends ça", "shimaore": "nissi renga ini", "kibouchi": "", "category": "expression", "image_url": "✋", "difficulty": 1},
        {"french": "combien la nuit ?", "shimaore": "kissagé oukou moja", "kibouchi": "", "category": "expression", "image_url": "🌙", "difficulty": 1},
        {"french": "avec climatisation ?", "shimaore": "ina climatisation", "kibouchi": "", "category": "expression", "image_url": "❄️", "difficulty": 1},
        {"french": "avec petit déjeuner ?", "shimaore": "ina kèya", "kibouchi": "", "category": "expression", "image_url": "🥞", "difficulty": 1},
        {"french": "appelez la police !", "shimaore": "hira sirikali", "kibouchi": "", "category": "expression", "image_url": "🚔", "difficulty": 1},
        {"french": "appelez une ambulance !", "shimaore": "hira ambulanci", "kibouchi": "", "category": "expression", "image_url": "🚑", "difficulty": 1},
        {"french": "j'ai besoin d'un médecin", "shimaore": "ntsha douktera", "kibouchi": "", "category": "expression", "image_url": "👩‍⚕️", "difficulty": 1},
        {"french": "je ne me sens pas bien", "shimaore": "tsissi fétré", "kibouchi": "", "category": "expression", "image_url": "😵", "difficulty": 1},
        {"french": "au milieu", "shimaore": "hari", "kibouchi": "", "category": "expression", "image_url": "🎯", "difficulty": 1},
        {"french": "respect", "shimaore": "mastaha", "kibouchi": "", "category": "expression", "image_url": "🙏", "difficulty": 1},
        {"french": "quelqu'un de fiable", "shimaore": "mwaminifou", "kibouchi": "", "category": "expression", "image_url": "🤝", "difficulty": 1},
        {"french": "secret", "shimaore": "siri", "kibouchi": "", "category": "expression", "image_url": "🤫", "difficulty": 1},
        {"french": "joie", "shimaore": "fouraha", "kibouchi": "", "category": "expression", "image_url": "😊", "difficulty": 1},
        {"french": "avoir la haine", "shimaore": "outoukiwa", "kibouchi": "", "category": "expression", "image_url": "😠", "difficulty": 1},
        {"french": "convivialité", "shimaore": "ouvoimoja", "kibouchi": "", "category": "expression", "image_url": "🤝", "difficulty": 1},
        {"french": "entre aide", "shimaore": "oussayidiyana", "kibouchi": "", "category": "expression", "image_url": "🤝", "difficulty": 1},
        {"french": "faire crédit", "shimaore": "oukopa", "kibouchi": "", "category": "expression", "image_url": "💰", "difficulty": 1},
        {"french": "nounou", "shimaore": "mlezi", "kibouchi": "", "category": "expression", "image_url": "👵", "difficulty": 1},

        # PAGE 11 - ADJECTIFS
        {"french": "grand", "shimaore": "bolé", "kibouchi": "", "category": "adjectif", "image_url": "📏", "difficulty": 1},
        {"french": "petit", "shimaore": "titi", "kibouchi": "", "category": "adjectif", "image_url": "📏", "difficulty": 1},
        {"french": "gros", "shimaore": "mtronga/tronga", "kibouchi": "", "category": "adjectif", "image_url": "🔵", "difficulty": 1},
        {"french": "maigre", "shimaore": "tsala", "kibouchi": "", "category": "adjectif", "image_url": "📏", "difficulty": 1},
        {"french": "fort", "shimaore": "ouna ngouvou", "kibouchi": "", "category": "adjectif", "image_url": "💪", "difficulty": 1},
        {"french": "dur", "shimaore": "mangavou", "kibouchi": "", "category": "adjectif", "image_url": "🪨", "difficulty": 1},
        {"french": "mou", "shimaore": "trémboivou", "kibouchi": "", "category": "adjectif", "image_url": "🧽", "difficulty": 1},
        {"french": "beau/jolie", "shimaore": "mzouri", "kibouchi": "", "category": "adjectif", "image_url": "😍", "difficulty": 1},
        {"french": "laid", "shimaore": "tsi ndzouzouri", "kibouchi": "", "category": "adjectif", "image_url": "😬", "difficulty": 1},
        {"french": "jeune", "shimaore": "nrétsa", "kibouchi": "", "category": "adjectif", "image_url": "👶", "difficulty": 1},
        {"french": "vieux", "shimaore": "dhouha", "kibouchi": "", "category": "adjectif", "image_url": "👴", "difficulty": 1},
        {"french": "gentil", "shimaore": "mwéma", "kibouchi": "", "category": "adjectif", "image_url": "😊", "difficulty": 1},
    ]
    
    # Ajouter timestamp à chaque mot
    for word in pdf_vocabulary:
        word["created_at"] = datetime.utcnow()
    
    # Insérer tous les mots
    result = words_collection.insert_many(pdf_vocabulary)
    
    print(f"✅ Base de données créée d'après le PDF : {len(result.inserted_ids)} mots ajoutés")
    
    # Vérification par catégorie
    categories = {}
    for word in pdf_vocabulary:
        cat = word["category"]
        if cat not in categories:
            categories[cat] = 0
        categories[cat] += 1
    
    print("\n📊 RÉPARTITION PAR CATÉGORIE :")
    total = 0
    for cat, count in sorted(categories.items()):
        print(f"   {cat}: {count} mots")
        total += count
    
    print(f"\n🎯 TOTAL : {total} mots exacts du fichier PDF")
    
    return len(result.inserted_ids)

if __name__ == "__main__":
    print("🔄 Création de la base de données à partir du fichier PDF...")
    count = create_database_from_pdf()
    print(f"✅ Terminé ! {count} mots créés selon le fichier PDF.")